### ISSUE TITLE
Sandbox testing for Giropay

### ISSUE THREAD

**Issue by saachitech** [checkout/checkout-sdk-node#176]
I am trying to simulate payment using Giropay in my sandbox env but I keep getting "business_not_onboarded" error. Not sure what I am missing anything, here is my code. 

const { Checkout } = require('checkout-sdk-node');

// Creating an environment
let secretKey = "SECRET_KEY_FROM_CHANNEL";
const cko = new Checkout(secretKey);

const createOrder = async () => {
  const response = await cko.payments.request({
    "source": {
      "type": "giropay",
      "purpose":"Mens black t-shirt L"
    },  
   "amount": 5,
   "currency": "EUR",
    "success_url": "https://example.com/pay/giropay/return",
    "failure_url": "https://example.com/pay/giropay/cancel",
  });
  console.log(`Response: ${JSON.stringify(response)}`);
  return response;
}

Here is the error I got
"body": {
    "request_id": "7e12e59f-a2c6-4b88-9a82-56f6b3113b4e",
    "error_type": "request_invalid",
    "error_codes": [
        "business_not_onboarded"
    ]
},

Not sure if the error is within SDK or I am missing some setting here. Please Help. Thanks

**Comment by ioan-ghisoi-cko** [comment]
Hi. By default, in your test account, the local payment options (like Giropay) are not enabled. If you reach out to integration@checkout.com we can enable this option for you. (or reach out to your customer success manager in case you are in Prod and looking to use a new payment method)

For reference, this is not an SDK issue.
