### ISSUE TITLE
Add the ability to search the documentation and cache for offline access.

### ISSUE THREAD

**Issue by ZiyadF296** [checkout/checkout-sdk-node#181]
Hello there 👋
It would be very helpful and nice if there was a search bar on the documentation website.
Also, since sometimes I do not have access to the internet connection, it would be nice to access the documentation offline.

Thanks in advance.

**Comment by ioan-ghisoi-cko** [comment]
Thank you for the feedback. I'll put this in the backlog and I'll look into it.

**Comment by Inrmanish** [comment]
@ZiyadF296 ,
see my pull req.
 if good then merge!

**Comment by ioan-ghisoi-cko** [comment]
Hi. The documentation will soon be migrated so no new updates will be made on the current version. Out [API Reference](https://api-reference.checkout.com/) has samples for all API calls with this SDK
