### ISSUE TITLE
Re-validating an event respond with not found error

### ISSUE THREAD

**Issue by saachitech** [checkout/checkout-sdk-node#188]
I am having a very weird issue here. I have implemented few Bank Transfer payments such as Giropay, Sofort. They all work fine. I have added a webhook to receive all notifications which are working great. The error appears when I try to re-validate the event I received. I always get the following error

![image](https://user-images.githubusercontent.com/2406252/128596612-9d639ec4-5fd6-4f30-ac68-2eaa92e7db82.png)
I have no idea why this is happening. Here is the code I am trying
```
const { Checkout } = require('checkout-sdk-node');
let cko = new Checkout("sk_test_xxxx");
let response = await cko.events.retrieveEvent('evt_xxxx')
```
Here I get the NotFound Error. 

I also tried to retrieve all events for a payment id using the following code but that tells me that there are no events for the payment
```
const { Checkout } = require('checkout-sdk-node');
let cko = new Checkout("sk_test_xxxx");
let response = await cko.events.retrieveEvents({payment_id:'pay_xxxxx'})
```

So I have no clue what's happening under the hood. I received the event fine but I am not able to verify it. Could someone please shed some light on this?

**Comment by ioan-ghisoi-cko** [comment]
This is an API behavior and it's not related to the SDK. Please ping integration@checkout.com, and we can help you in the email thread.
