### ISSUE TITLE
Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by maimona-issam-cko** [checkout/checkout-sdk-node#265]
Hi Team, 

I have been helping a merchant with their integration and they've been facing CROS issue.

According to the developer, they’re facing this error on local and on server

The following are the errors in local development:

  "Access to fetch at ‘https://api.sandbox.checkout.com/tokens’ from origin ‘http://localhost:4200’ has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response."

The following are the error in server:
  "Access to fetch at ‘https://api.sandbox.checkout.com/tokens’ from origin ‘https://prologix-test.web.app’ has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.”

This is what they’re using:

- Node : 14.17.6
- Angular CLI: 12.2.5
- Checkout sdk node: 1.0.37

I have also asked for the HAR file for the requests, look [here](https://drive.google.com/drive/folders/1OW8FMmAiAWP3S66BwMmnpz-jR9QUuxzu?usp=sharing).

I can see that in our sdk, we’re adding the pragma parameter in file /src/services/http.js line 43

**Comment by ioan-ghisoi-cko** [comment]
Hi. 

You have a diagram here that described the general payment flow -> https://www.checkout.com/docs/integrate/frames#How_it_works

The idea here is that if you do not have a higher level of PCI Compliance, you need to use one of our integration options like Frames to collect the card details securely on the client-side. Frames return a card token (tok_XXXX) that you can send to your server-side and then use the Node SDK to send a payment request. 

You should have an environment like an express server serving your angular app, and handling your interactions with the API.
