### ISSUE TITLE
Major version bump 1 > 2 breaking changes?

### ISSUE THREAD

**Issue by jamie-phlo** [checkout/checkout-sdk-node#275]
I've tried to find the changelog as I'm wanting to know what, if any, breaking changes were include in the v2 major bump?

We're planning on bumping shortly and want to know if I can expect any breaking changes or changes to how we use the package in production.

@ioan-ghisoi-cko I saw you performed the bump, do you know? 

Thanks.

**Comment by ioan-ghisoi-cko** [comment]
No breaking change. Feel free to use the latest. As always, please make sure you test things in Sandbox to validate there is no impact before you push to Prod.
