### ISSUE TITLE
Incremental authorisation method Payments.increment doesn't expose idempotencyKey

### ISSUE THREAD

**Issue by jkowald-gc** [checkout/checkout-sdk-node#280]
Unlike 
Payments.request (body, idempotencyKey)
and
Payments.capture(paymentId, body, idempotencyKey) 
the 
Payments.increment(paymentId, body) 
method doesn't allow specification of an idempotency key. Since the body contains an incremental authorisation amount, the effect of a replayed transaction is to double-increment.

Additionally, and differently from the documentation, the returned payment object doesn't contain reference, metadata or a status field (example attached)

[increment.txt](https://github.com/checkout/checkout-sdk-node/files/9713255/increment.txt)

**Comment by ioan-ghisoi-cko** [comment]
Thanks for raising this. I'll add a fix ASAP.

**Comment by ioan-ghisoi-cko** [comment]
Fixed in 2.0.3
