### ISSUE TITLE
 error TS2300: Duplicate identifier 'addPaymentInstrument'.

### ISSUE THREAD

**Issue by srcarlos** [checkout/checkout-sdk-node#308]
Hello, I am using the latest version of checkout-sdk-node (2.1.0) and at the time of build. I have the following error:

![Checkout SDK Error](https://user-images.githubusercontent.com/5458009/213253515-912a9962-8b4f-48d0-9684-8e0852e8eede.PNG)

Looking at the build source code, I see that the function is duplicated  **addPaymentInstrument**

![CHECKOUT SDK](https://user-images.githubusercontent.com/5458009/213253301-63b8f103-fed9-4852-b958-95601409f28a.PNG)

I sent a PR to fix this error but I'm not sure if it fixes it at all. 

[PR](https://github.com/checkout/checkout-sdk-node/pull/305)

**Comment by Armando-Ibarra** [comment]
Hi @srcarlos this was merged and released
Thanks for your contribution, let us know if you face any other issue :)
