### ISSUE TITLE
Add types property to package.json

### ISSUE THREAD

**Issue by Repugraf** [checkout/checkout-sdk-node#356]
If the package has `types` property in `package.json` pointing to `d.ts` file it will have `ts` icon on npm page indicating it has build in typescript types.

For example here is the [chalk package](https://www.npmjs.com/package/chalk)

<img width="1551" alt="Screenshot 2023-08-08 at 19 34 48" src="https://github.com/checkout/checkout-sdk-node/assets/43890857/66df81eb-6c57-4f1e-bb22-acd380246eec">

And here is how their `package.json` looks like:

<img width="861" alt="Screenshot 2023-08-08 at 19 36 47" src="https://github.com/checkout/checkout-sdk-node/assets/43890857/0436c43b-016d-44eb-8175-c0d3176176e1">

So for this package to have the same icon on npm `types` property should be added to `package.json` with the value of `./types/dist/index.d.ts`.

This should be really easy to do.

**Comment by armando-rodriguez-cko** [comment]
Thank you @Repugraf, we are taking a look it together with https://github.com/checkout/checkout-sdk-node/pull/357.

**Comment by armando-rodriguez-cko** [comment]
Thank you @Repugraf, we have a future task to introduce these improvements, at the moment we cannot do it, thank you very much, we will take it into account and write it down.
