### ISSUE TITLE
Missing Checkout features compared to Checkout SDKs in other languages 

### ISSUE THREAD

**Issue by Zekdar** [checkout/checkout-sdk-node#360]
Hello,

I'm currently planning on implementing Checkout in my Node app.
After having a look at the documentation, I have seen that some actions are missing in the Node SDK compared to the Java or C# one (for instance).
Example : [Standalone Authentication](https://api-reference.checkout.com/#tag/Standalone)

I have some questions : 
- Are you planning on implementing the same features as other languages ?
  - If so, do you have a public roadmap ?
- Do you accept pull requests ?

Thanks !

**Comment by armando-rodriguez-cko** [comment]
Hi @Zekdar! 
Thanks for your questions. At the moment we do not have a public roadmap and these features will be implemented in the future, but we cannot provide an ETA.
Regarding the second question, yes, we accept pull requests.
