### ISSUE TITLE
Audit runtime dependency

### ISSUE THREAD

**Issue by mitja-kramberger-cko** [checkout/checkout-sdk-node#38]
`codecov` is defined as runtime dependency even though is a development utility (for uploading code coverage reports). Also, the currently used version has a security vulnerability. I would encourage us to also remove / audit `babel` as runtime dependency as it most probably only used during build time.

**Comment by ioan-ghisoi-cko** [comment]
Check the [latest release](https://github.com/checkout/checkout-sdk-node/releases/tag/v1.0.18).
